services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: my_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - backend-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./src/main/kotlin:/app/src/main/kotlin
            - ./src/main/resources:/app/src/main/resources
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/my_database
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=password
        depends_on:
            - db
        networks:
            - backend-network

networks:
    backend-network:
        driver: bridge
