services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: my_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 3

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./src/main/kotlin:/app/src/main/kotlin
            - ./src/main/resources:/app/src/main/resources
            - ./backend/build:/app/build # コンパイル済みファイルを反映
            - ~/.m2:/root/.m2 # ローカルのMavenキャッシュ共有で依存関係のダウンロードを高速化
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/my_database
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root_password
            - JAVA_OPTS=-Dspring.devtools.restart.enabled=true # DevToolsの再起動機能を明示的に有効化
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network
        command: ./gradlew bootRun # ホットリロード対応のための起動コマンド

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        volumes:
            - ./frontend:/app
        command: npm run dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
