services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: my_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 3

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
            - ~/.m2:/root/.m2 # Mavenキャッシュを共有
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/my_database
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root_password
            - SPRING_DEVTOOLS_RESTART_ENABLED=true
            - SPRING_DEVTOOLS_RESTART_TRIGGER_FILE=.reload
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network
        command: ./gradlew bootRun
        container_name: backend

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
            - API_BASE_URL=http://backend:8080
        networks:
            - app-network
        volumes:
            - ./frontend:/app
        command: npm run dev
        container_name: frontend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
