services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: my_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./src/main/kotlin:/app/src/main/kotlin
            - ./src/main/resources:/app/src/main/resources
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/my_database
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root_password
        depends_on:
            - db
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
