name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"] # CI の成功をトリガー
        types:
            - completed

jobs:
    cd:
        name: Deploy with Terraform
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Initialize Terraform
              run: terraform init
              working-directory: ./terraform

            - name: Validate Terraform
              run: terraform validate
              working-directory: ./terraform

            - name: Plan Terraform
              id: plan
              run: terraform plan -out=tfplan
              working-directory: ./terraform

            - name: Apply Terraform
              run: terraform apply -auto-approve tfplan
              working-directory: ./terraform
