name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    uses: ./.github/workflows/ci-frontend.yml

  backend:
    uses: ./.github/workflows/ci-backend.yml