name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-backend.yml

  deploy:
    needs: [ci]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # appdir: "backend"
          procfile: "web: java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/*.jar"