name: Deploy to ECS

on:
    push:
        branches:
#            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push Docker image to Amazon ECR
              run: |
                  IMAGE_TAG=$GITHUB_SHA
                  docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
                  docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

            - name: Deploy to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
                  task-definition: task-definition.json
                  service: rankify-hub-service
                  cluster: ecs-integrated
                  wait-for-service-stability: true
