name: CI/CD Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Log in to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Build, Tag, and Push Docker Image
                run: |
                    docker build -t ${{ secrets.ECR_REPOSITORY }} .
                    docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
                    docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    terraform-deploy:
        name: Terraform Deploy
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v2
                with:
                    terraform_version: 1.5.3

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}

            -   name: Terraform Init
                working-directory: ./terraform
                run: terraform init

            -   name: Terraform Plan
                working-directory: ./terraform
                run: terraform plan

            -   name: Terraform Apply
                working-directory: ./terraform
                run: terraform apply -auto-approve
