name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - "**/Dockerfile"
      - "backend/**" # Dockerイメージに関連する変更があるファイルやディレクトリを指定
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rankify-hub:latest .

      - name: Push to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rankify-hub:latest

      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs-task-definition.json # 必要に応じてタスク定義ファイルを指定
          service: rankify-hub-service
          cluster: rankify-hub-cluster
          region: ${{ secrets.AWS_REGION }}
          wait-for-service-stability: true
